#' Extract comparative statistics from two presence/absence RasterLayers.
#'
#'
#' Extract metrics of range size change, seasonality, and centroid distance
#' from two presence/absence surfaces. Such surfaces are often generated by
#' thresholding a continuous probability-of-origin surface for conversion to a
#' binary surface.
#'
#' RasterLayers must have identical resolutions and extents.
#'
#' @param PA1 Presence/absence RasterLayer from season 1
#' @param PA2 Presence/absence RasterLayer from season 2
#' @param ... Additional arguments to append to the returned data.frame
#'
#' @importFrom raster compareRaster
#' @importFrom raster reclassify
#' @importFrom stars st_as_stars
#' @importFrom sf st_as_sf
#' @importFrom sf st_combine
#' @importFrom sf st_make_valid
#' @importFrom sf st_intersection
#' @importFrom sf st_difference
#' @importFrom sf st_union
#'
#' @return A data.frame containing presence-absence surface based metrics
#'
#' @export
extractPAstatistics <- function(PA1, PA2, ...) {
  stopifnot(
    {"Class of PA1 and PA2 must be the same" = class(PA1) == class(PA2) },
    {"Class of PA arguments must be RasterLayer" = class(PA1) == c("RasterLayer")},
    {"PA1 and PA2 must have identical extent and resolutions" =
      !raster::compareRaster(PA1, PA2) }
    )

  PA_sf1 <- PA1 %>%
    raster::reclassify( matrix(c(-Inf,0.5,NA), ncol = 3, byrow = T)) %>%
    # Convert to stars
    stars::st_as_stars() %>%
    # Convert to sf
    sf::st_as_sf(merge = T) %>%
    sf::st_combine() %>%
    sf::st_make_valid()
  PA_sf2 <- PA2 %>%
    raster::reclassify( matrix(c(-Inf,0.5,NA), ncol = 3, byrow = T)) %>%
    # Convert to stars
    stars::st_as_stars() %>%
    # Convert to sf
    sf::st_as_sf(merge = T) %>%
    sf::st_combine() %>%
    sf::st_make_valid()

  # Range size change
  area_1 <- sf::st_area(PA_sf1)
  area_2 <- sf::st_area(PA_sf2)
  rangeSizeChange <- area_1 / area_2

  # Year round v.s. seasonal
  area_yrRound  <- sf::st_intersection( PA_sf1, PA_sf2 ) %>% sf::st_area() %>% as.numeric()
  area_s1only   <- sf::st_difference(   PA_sf1, PA_sf2 ) %>% sf::st_area() %>% as.numeric()
  area_s2only   <- sf::st_difference(   PA_sf2, PA_sf1 ) %>% sf::st_area() %>% as.numeric()
  area_seasonal <- area_s1only + area_s2only
  area_all      <- sf::st_union( PA_sf1, PA_sf2 ) %>% sf::st_area() %>% as.numeric()
  yrRoundVseasonal <- as.numeric( (area_seasonal / area_all) - (area_yrRound / area_all) )

  # Centroid distance.
  centroidDistPA_km <- sf::st_distance(sf::st_centroid(PA_sf1), sf::st_centroid(PA_sf2))
  units(centroidDistPA_km) <- "km"

  # data.frame with returned details.
  df <- data.frame(
    ...,
    PA_rangeSizeChange = rangeSizeChange,
    PA_yrRoundVseasonal = yrRoundVseasonal,
    PA_centroidDist_km = centroidDistPA_km
  )
  return(df)
}
